#!/bin/bash

# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
# TODO: 
# - Make hooks for preventing to merge main if it is not sync with origin

# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
# Prevent direct commits on main
branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch, only merge"
  exit 1
fi