#!/bin/bash

# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
# TODO: 
# - Make hooks for preventing to merge main if it is not sync with origin
# - Force work on `git config --global user.name` branch
# - Place in this same folder and `install hooks` script that create the 
# `.git/hooks/` entry points
# - Applicaion: Modify a repo README before push


# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
if [[ "${_GITHOOKS_IGNORE}" -eq 1 ]]; then
    echo "IGNORING HOOKS"
    echo "Set `export _GITHOOKS_IGNORE=1` to force"
    exit 0 
fi

# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
# Keep all updated
git fetch &

# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
# Prevent direct commits on main
branch="$(git rev-parse --abbrev-ref HEAD)"

if [[ "$branch" = "main" ]]; then
  echo "You can't commit directly to main branch, only merge"
  exit 1
fi

