#!/bin/sh

# -- .- -. .- - - .-. -. -.. .- - -- . -- .- -.-.- 
# PER-MERGE
MERGE_MSG_FILE="${GIT_HOOKS_CALLERS_DIR}/../MERGE_MSG"
if [ -f "${HOOK_FILE}" ]; then
	echo "PRE-MERGE-COMMIT HOOKS"
	HOOK_FILE="${GIT_HOOKS_SRC_DIR}/pre-merge-commit"
	if [ -f "${HOOK_FILE}" ]; then
		source "${HOOK_FILE}"
	fi
fi